<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ไอดี',
    'Lang ID' => 'รหัสภาษา',
    'Lang' => 'ภาษา',
    'Name' => 'ชื่อ',
    'Created By' => 'ชื่อผู้สร้าง',
    'Created Date' => 'วันที่สร้าง',
    'Modified By' => 'ชื่อผู้แก้ไข',
    'Modified Date' => 'วันที่แก้ไข',
    'Ctt Staticdata Countrys' => 'รายการประเทศ',
    'Ctt Staticdata Countrys(Language List)' => 'รายการประเทศ (ภาษา)',
    'Create Country' => 'สร้างประเทศ',
    'Add new language' => 'เพิ่มภาษาใหม่',
    'Create Ctt Staticdata Countrys' => 'เพิ่มประเทศ',
    'Update Ctt Staticdata Countrys' => 'แก้ไขประเทศ',
];