<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    // Model
    'Documenttype ID' => 'Documenttype ID',
    'Documenttype' => 'Documenttype',
    'Docsource ID' => 'Docsource ID',
    'Docsource' => 'Docsource',
    'Alias ID' => 'Alias ID',
    'Title' => 'Title',
    'Abbrev Title' => 'Abbrev Title',
    'Title Fulltext' => 'Title Fulltext',
    'Publisher ID' => 'Publisher ID',
    'Journal ID' => 'Journal ID',
    'Journal' => 'Journal',
    'Issue ID' => 'Issue ID',
    'Year' => 'Year',
    'Volume' => 'Volume',
    'Artnumber' => 'Artnumber',
    'Page Start' => 'Page Start',
    'Page End' => 'Page End',
    'Page Count' => 'Page Count',
    'Cited' => 'Cited',
    'Doi' => 'DOI',
    'Link' => 'Link',
    'Organization ID' => 'Organization ID',
    'Organization' => 'Organization',
    'Abstract' => 'Abstract',
    'Abstract Fulltext' => 'Abstract Fulltext',
    'Author Keyword' => 'Author Keyword',
    'Auto Keyword' => 'Auto Keyword',
    'Authors' => 'Authors',
    'Funding' => 'Funding',
    'Correspondence' => 'Correspondence',
    'Sponsors' => 'Sponsors',
    'Codenid' => 'CODEN ID',
    'Pubmedid' => 'Pubmed ID',
    'Checksum' => 'Checksum',
    'Subjectarea Class' => 'Subjectarea',
    'Status' => 'Status',
    'Created By' => 'Created By',
    'Created Dtm' => 'Created Dtm',
    'Modified By' => 'Modified By',
    'Modified Dtm' => 'Modified Dtm',
    // UI
    // 'Ctt Journals' => 'Journal List',
    // 'Create Ctt Journals' => 'Create Journal',
    // 'Update Ctt Journals' => 'Update Journal',
];