<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	// Model
    'Alias ID' => 'Alias ID',
    'Name' => 'Name',
    'Name Fulltext' => 'Name Fulltext',
    'Abbrev Name' => 'Abbrev Name',
    'Issn' => 'ISSN',
    'Eissn' => 'EISSN',
    'Isbn' => 'ISBN',
    'Coverage' => 'Coverage',
    'Editor' => 'Editor',
    'Open Status' => 'Open Status',
    'Access Status' => 'Access Status',
    'Source Type ID' => 'Source Type ID',
    'Source Type' => 'Source Type',
    'Print Lang' => 'Print Lang',
    'Volume Per Year' => 'Volume Per Year',
    'Issue Per Volume' => 'Issue Per Volume',
    'History Indication ID' => 'History Indication ID',
    'History Indication' => 'History Indication',
    'Address' => 'Address',
    'Country ID' => 'Country ID',
    'Phone' => 'Phone',
    'Fax' => 'Fax',
    'Email' => 'Email',
    'Website' => 'Website',
    'Publisher ID' => 'Publisher ID',
    'Subjectarea Class' => 'Subjectarea Class',
    'Organization ID' => 'Organization ID',
    'Organization' => 'Organization',
    // UI
    'Ctt Journals' => 'Journal List',
    'Create Ctt Journals' => 'Create Journal',
    'Update Ctt Journals' => 'Update Journal',
];