<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => 'ID',
    'Lang ID' => 'Lang ID',
    'Lang' => 'Lang',
    'Name' => 'Name',
    'Created By' => 'Created By',
    'Created Date' => 'Created Date',
    'Modified By' => 'Modified By',
    'Modified Date' => 'Modified Date',
    'Ctt Staticdata Country' => 'Ctt Staticdata Countrys',
    'Ctt Staticdata Countrys(Language List)' => 'Ctt Staticdata Countrys (Language List)',
    'Create Country' => 'Create Country',
    'Add new language' => 'Add new language',
    'Create Ctt Staticdata Countrys' => 'Create Ctt Staticdata Countrys',
    'Update Ctt Staticdata Countrys' => 'Update Ctt Staticdata Countrys',
];